# Project info
site_name: IronOS
site_url: https://ralim.github.io/IronOS/
site_description: "IronOS firmware customized for the Miniware TS101"

# Repo config
repo_url: https://github.com/ralim/IronOS/

# Dir & location config
docs_dir: ../documentation
edit_uri: edit/dev/documentation/

# Theme and config
theme:
  name: readthedocs
  highlightsjs: true
  hljs_languages:
    - yaml

# Navigation structure
nav:
  - Home: index.md
  - Getting Started: GettingStarted.md
  - Flashing the firmware: flashing/TS101.md
  - Operation:
      - Main Menu: Menu.md
      - Settings: Settings.md
      - Debug Menu: DebugMenu.md
      - Power: Power.md
      - Temperature: Temperature.md
  - Startup Logo: Logo.md
  - Hardware:
      - Debugging USB-PD: DebuggingPD.md
      - Hardware Notes: Hardware.md
      - Known Hardware Issues: HardwareIssues.md
      - New Hardware Requirements: PortingToNewDevice.md
      - Power sources: PowerSources.md
      - Troubleshooting: Troubleshooting.md
  - Translations: Translation.md
  - Development: Development.md
  - Changelog: History.md

# Plugins
plugins:
  - search
  - autolinks
  - awesome-pages
  - git-revision-date

# Markdown Extensions
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
